# labs/lab02/Makefile
.PHONY: ex1 ex2 ex3

ex1:
	cargo run --bin ex01_fillme

ex2:
	cargo run --bin ex02_fillme

# if this one will be GUI-heavy, mirror lab01’s flags; change the bin name later
ex3:
	cargo run --features gui --release --bin ex3_fillme_gui
