# labs/lab03/Makefile
.PHONY: ex1

# Usage:
#   make ex1                      # prompts for input
#   cargo run --bin ex01_tm -- ACTG 0.1   # with args (DNA and [Na+] in M)

ex1:
	cargo run --bin ex01_tm
